### PR TITLE
Made changes for the reporting service

### PR DESCRIPTION
**Pull request by anderslarsson**
Added an icon for the reporting application and added a link in the admin menu to the reporting configuration page.

### CODE REVIEW

**Comment by kwierchris** [comment]
Who approved that the reporting access should be a dedicated application icon?

**Comment by anderslarsson** [comment]
The icon was a request from the business (Jennie Klaesson). Was discussed at some point with Arne. Is there an alternative?

**Comment by kwierchris** [comment]
Then tell them next time to ask me first because I am responsible for this.

**Comment by anderslarsson** [comment]
I will forward that information. Thanks

**Comment by kwierchris** [comment]
If you want, I can approve that but this changes will only be available if you're using service-base-ui v2.x but some of the functions there are not working without the migration of the platform to business partner.

**Comment by anderslarsson** [comment]
We're using version 1.1.128. Is there are branch where I can push the changes instead? Can't find any tag for that version.

**Comment by anderslarsson** [comment]
How can I provide the changes to you? We are adding a report icon linking to the application, adding reporting in the admin menu. The icon is based on svg-icon 1.1.5 version.

**Comment by anderslarsson** [comment]
In the commit 909a61e:
service-base-ui/components/MainMenu/data/navItems/admin.js line 70
        {
            "key": "reporting",
            "label": "Reporting",
            "link": "/reporting/config"
        }
service-base-ui/components/MainMenu/MainMenu.react.js line 440
        applicationItems.push({
            label : 'Reporting',
            icon : this.getIcon('reporting_service'),
            onClick : () => router.push('/reporting'),
            id : '/reporting'
        }); 
package.json change to "@opuscapita/svg-icons": "^1.1.5"

Maybe it's better do get the changes in some other way. Please let me know!

**Comment by kwierchris** [comment]
I published a retrofit version as @opuscapita/service-base-ui@1.1.129. Please try.

**Comment by anderslarsson** [comment]
I've tested it and it builds but there is an error somewhere while loading. I enabled paus on exception in dev console and the last error that it stops at (while the spinner shows) is issupplier is not a property of undefined. Is that a hint?

**Comment by anderslarsson** [comment]
Yes, I can confirm that in the 1.1.128 service-base-ui bundle.js there is no issupplier but in 1.1.129 there is.

**Comment by kwierchris** [comment]
Integrated manually due to legacy branch compatibility.

**Pull request closed without merging**
