### PR TITLE
Feature/genesis 166 blank screen for norwegian

### PR DESCRIPTION
**Pull request by jacekWojcikOpusCapita**
This is a new pull request dealing with the same ticket, previous PR is already closed.

old PR: https://github.com/OpusCapita/service-base-ui/pull/87
ticket: https://opuscapita.atlassian.net/browse/GENESIS-166

Ticket description:

"
Current behavior
When the user.userProfile -> languageId attribute includes a non supported value, the MainMenu breaks and it renders a blank page.

Expected behavior
When there user's profile includes a non-supported languageId, ie. norwegian("no") or danish("da") , it should load the Menu items in English.
"

### CODE REVIEW

**Review by nczeranka — DISMISSED** [review]
If develop is out of date, then please start with merging master to develop - and then start branching on the updated develop branch.
I did it for you. Now we can see your changes.

Why do you think that this will solve the problem? Isn't recursiveMergeNavItems able to deal with this situation?

**Comment by jacekWojcikOpusCapita** [comment]
The purpose of `recursiveMergeNavItems` is to merge one thing with another.
When we do not have `another thing` then this function should not be even called because it does not make sense to be called.

And it should be enough to stick to my solution.

If you ask if why `recursiveMergeNavItems` is not able to deal with this situation the answer is here:

`const overlay = overlays.find(overlay => overlay.key === item.key);`

as you can see it is `undefined.find` scenario.

**Comment by nczeranka** [comment]
A method/function that is called should always be able to deal with given parameters properly. This could also mean that this method/function throws an error.

But here we don't want to deal with Exceptions. Instead the method recursiveMergeNavItems has to handle even wrong parameters properly.
Please add proper handling to the method and omit additional checks when calling it.

**Comment by jacekWojcikOpusCapita** [comment]
It should not be called when it should not be called.
Anyway, let's do it your way.

**Review by nczeranka — APPROVED** [review]

**Pull request merged**
