### PR TITLE
(GENESIS-1262) Move react and react-dom to peerDependencies

### PR DESCRIPTION
**Pull request by KacperKlosowskiOC**
Jira: https://opuscapita.atlassian.net/browse/GENESIS-1262
-----
Having react and react-dom is blocking us while trying to bump up react in other services. Better option is to move it as peerDepedencies and tell that service-base-ui is compatible with v15 and v16 version.

### CODE REVIEW

**Review by ElaCzapiewska — APPROVED** [review]
Let's try :)

**Comment by KacperKlosowskiOC** [comment]
Instead of merging the changes right away to the 'latest' version, I created 'next' tagged version: 1.1.184-next.1, which will be used for testing purposes. If it's working as expected, then I will merge this.

**Comment by KacperKlosowskiOC** [comment]
React in iso-data and business-partner will be updated by @ElaCzapiewska and @LuizaMarcinkowska soon.

If those 2 services will be updated, then there's no need to remove switch tenant feature from service-base-ui.

I decide not to merge this pull request for now. Let's have an experimental version of service-base-ui with tag **next**, where you have React^16 and no switch tenant feature, and after React update in bp and iso-data we can have new service-base-ui version with tag **latest** and only peerDependencies change.

**Comment by KacperKlosowskiOC** [comment]
PeerDeps change was introduced in  https://github.com/OpusCapita/service-base-ui/pull/121, so I'm closing this one.

**Pull request closed without merging**
